Catch JsonSyntaxException for (Temporary)AllowlistModel
A user on Matrix reported a crash in the TemporaryAllowlistModel parsing:

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
com.google.gson.Gson.fromJson(Gson.java:1372)
com.google.gson.Gson.fromJson(Gson.java:1306)
de.nulide.findmydevice.data.TemporaryAllowlistRepository.<init>(TemporaryAllowlistRepository.kt:46)
de.nulide.findmydevice.data.TemporaryAllowlistRepository.<init>(Unknown Source:0)
de.nulide.findmydevice.data.TemporaryAllowlistRepository$Companion$1.invoke(TemporaryAllowlistRepository.kt:34)
de.nulide.findmydevice.data.TemporaryAllowlistRepository$Companion$1.invoke(TemporaryAllowlistRepository.kt:34)
de.nulide.findmydevice.utils.SingletonHolder.getInstance(SingletonHolder.kt:35)
de.nulide.findmydevice.services.TempContactExpiredService.onStartJob(TempContactExpiredService.java:25)
android.app.job.JobService$1.onStartJob(JobService.java:118)
android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:171)
android.os.Handler.dispatchMessage(Handler.java:109)
android.os.Looper.loopOnce(Looper.java:232)
android.os.Looper.loop(Looper.java:317)
android.app.ActivityThread.main(ActivityThread.java:8787)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
```

Clearing the temporary allowlist has basically no side effect (users just need to send the PIN again).

Clearing the allowlist is bad. But still better than not being able to use FMD at all (due to it crashing).
Hence notify the user.