Use android.util.Base64 instead of dependency
We don't need a dependency for something that Android already provides.

Also, this fixes a crash when decrypting commands from the server
that was introduced by minification:

> javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found

Alternatively, we could fix ProGuard to not remove that.
But it's simpler to just use android.util.Base64.